version: 2
updates:
  # Checks the actions in .github/workflows for new versions once a week.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
