# This workflow shows how "concurrency" prevents multiple runs from being
# active at the same time. If it's started a second time while the first
# run is still active, "cancel-in-progress" cancels the first run.
name: Concurrency Demo

on:
  workflow_dispatch:

# All runs with the same "group" share this rule.
concurrency:
  group: concurrency-demo
  cancel-in-progress: true

jobs:
  simulate-long-task:
    name: Simulate long task
    runs-on: ubuntu-latest
    steps:
      # To try it out: start this workflow manually twice in quick succession.
      # The first run gets cancelled as soon as the second one starts.
      - name: Wait and print output
        run: |
          echo "Task started..."
          sleep 30
          echo "Task completed."
