# This name is shown in the GitHub UI under "Actions".
name: Test Runner

# "on" defines which event triggers the workflow.
on:
  push:
    # The workflow only runs for changes pushed to "main".
    branches: [main]

# "jobs" holds the tasks the workflow runs.
jobs:
  # "build" is the freely chosen, internal ID of this job.
  build:
    # GitHub provides a current Ubuntu VM for the job.
    runs-on: ubuntu-latest
    steps:
      # Loads the content of this repository onto the VM.
      - uses: actions/checkout@v4
      - name: Display runner details
        # "run" executes a shell command. runner.os is a GitHub context variable.
        run: echo "Workflow is running on ${{ runner.os }}"
